[package]
name = "dom5status"
version = "0.1.0"
authors = ["David McGillicuddy <contact@djmcgill.co.uk>"]

[dependencies]
serenity = {version = "0.4.6", features = ["default"]}
hex-slice = "*"
flate2 = "1.0"
byteorder = "*"
typemap = "0.3"
url = "1.6.*"
futures = "0.1.17"
tiberius = "0.2.2"
tokio-core = "0.1.11"
