[package]
name = "dom5status"
version = "0.1.0"
authors = ["David McGillicuddy <contact@djmcgill.co.uk>"]

[dependencies]
serenity = {version = "0.4.6", features = ["default"]}
hex-slice = "*"
flate2 = "1.0"
byteorder = "*"
typemap = "0.3"
url = "1.6.*"
bincode = "0.9.2"
rusqlite = {version = "0.13.*", features = ["bundled"]}
lazy_static = "*"
r2d2 = "0.8.2"
r2d2_sqlite = "0.5.0"
