version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
          key: cargo-cache
      - run: cargo build
      - run: cargo test
      # TODO: coverage https://abronan.com/building-a-rust-project-on-circleci/
      - save_cache:
          key: cargo-cache
          paths:
            - "~/.cargo"
            - "./target"
            - "/usr/local/cargo"

  deploy:
    docker:
      - image: circleci/python # just something small that includes ssh
    steps:
      - add_ssh_keys
      - run:
          name: SSH to server and deploy
          command: |
            ssh -o "StrictHostKeyChecking=no" \
                   "$SSH_ADDRESS" \
                   "docker exec \"$CONTAINER_ID\" bash -ec 'git pull; cargo install --force'; docker restart \"$CONTAINER_ID\""

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
