version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
          key: cargo-cache
      - run: cargo build
      - run: cargo test
      - save_cache:
          key: cargo-cache
          paths:
            - "~/.cargo"
            - "./target"

# todo: test and coverage: https://abronan.com/building-a-rust-project-on-circleci/