version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
          key: cargo-cache
      - run: cargo build
      - run: cargo test
      # TODO: coverage https://abronan.com/building-a-rust-project-on-circleci/
      - save_cache:
          key: cargo-cache
          paths:
            - "~/.cargo"
            - "./target"

  deploy:
    docker:
      - image: fedora:latest
    steps:
      - run: yum -y install openssh-clients
      - add_ssh_keys:
          fingerprints:
            - "1e:e9:40:25:3a:70:3d:6c:5f:04:51:6d:81:ed:2a:32"
      - run:
          name: SSH to server and deploy
          command: |
            ssh -o "StrictHostKeyChecking=no" $SSH_ADDRESS
            ssh "$SSH_ADDRESS" "docker exec \"$CONTAINER_ID\" 'git pull; cargo install --force; exit'; docker restart \"$CONTAINER_ID\"; exit"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
